"""empty message

Revision ID: d073b4de326e
Revises: 
Create Date: 2021-04-28 01:46:05.624227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd073b4de326e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uId', sa.Integer(), nullable=False),
    sa.Column('uEmail', sa.String(length=100), nullable=False),
    sa.Column('uFirstName', sa.String(length=100), nullable=False),
    sa.Column('uLastname', sa.String(length=100), nullable=False),
    sa.Column('uPassword', sa.String(length=100), nullable=False),
    sa.Column('uSeed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uId'),
    sa.UniqueConstraint('uEmail')
    )
    op.create_table('notes',
    sa.Column('nId', sa.Integer(), nullable=False),
    sa.Column('nTitle', sa.String(length=50), nullable=False),
    sa.Column('nOwner', sa.Integer(), nullable=True),
    sa.Column('nDate_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nOwner'], ['users.uId'], ),
    sa.PrimaryKeyConstraint('nId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('users')
    # ### end Alembic commands ###
